#! /bin/sh

export EDITOR=nvim
export QT_QPA_PLATFORMTHEME="qt5ct"  

xinput --set-prop "ELAN1300:00 04F3:3087 Touchpad" "libinput Natural Scrolling Enabled" 1 &
setxkbmap -option grp:alt_shift_toggle us,es &
xsetroot -cursor_name left_ptr &
unclutter &
nitrogen --restore
picom -f -b &
light -S 50 &
$HOME/.config/polybar/launch.sh &
$HOME/.config/scripts/thunar.sh &
xss-lock -l $HOME/.config/scripts/lock.sh &
xfce4-power-manager &
blueberry-tray &
nm-applet &
gnome-keyring-daemon --start --components=pkcs11 &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII #VIII IX X

bspc config border_width          2

# Dracula theme
bspc config normal_border_color   '#282a36'
bspc config active_border_color   '#44475a'
bspc config focused_border_color  '#282a36'
bspc config presel_feedback_color '#282a36'

# Monokai soda theme
#bspc config normal_border_color		'#1a1a1a'
#bspc config active_border_color		'#303030'
#bspc config focused_border_color	'#1a1a1a'
#bspc config presel_feedback_color	'#1a1a1a'

# Nord Theme
#bspc config normal_border_color		'#2e3440'
#bspc config active_border_color		'#3b4252'
#bspc config focused_border_color	'#88c0d0'
#bspc config presel_feedback_color	'#434c5e'

bspc config top_padding 		      45
bspc config bottom_padding 		    0
bspc config left_padding 		      0
bspc config right_padding 		    0

bspc config honor_size_hints		  true

bspc config window_gap            15

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc config ignore_ewmh_focus 		false

bspc config focus_follows_pointer true

bspc rule -a firefox desktop='^1' follow=on
bspc rule -a kitty desktop='^2' follow=on
bspc rule -a Alacritty desktop='^2' follow=on
bspc rule -a Thunar desktop='^3' follow=on
bspc rule -a mpv state=floating follow=on focus=on
bspc rule -a Galculator state=floating
